### ISSUE TITLE
Difference between mesh extraction with refinement and without

### ISSUE THREAD

**Issue by Sidd1609** [Anttwo/SuGaR#101]
Hi, I like your work, and the code is written very well. Thank you so much for your contributions. I am looking to play around with the codebase to understand the algorithm in detail. 

Was hoping to know what is the observed difference with refining the Sugar model before mesh extraction and without. Does it actually help with more pleasing quality of mesh ?

**Comment by Anttwo** [comment]
Hi @Sidd1609,

Thank you so much for your nice words!

Before answering your question, here a few details about the different steps involved in SuGaR:

0. **Train a Vanilla Gaussian Splatting** for 7000 iterations (useful to let Gaussians densify and position themselves)
1. **SuGaR coarse optimization stage**: We continue optimizing the GS, but we add new optimization terms that enforce Gaussians to align with the surface. This part is very important for getting a good-looking mesh.
2. **Coarse mesh extraction**: We extract a mesh from the Gaussian Splatting. We call this mesh "_coarse_", but the surface is generally already pretty good and close to the final results.
3. **SuGaR refinement**: The refinement part has two goals: (a) Smoothing the surface of the mesh to get a slightly better result, and (b) build a hybrid representation mesh + Gaussians. To this end, we instantiate thin Gaussians on the surface of the mesh (we use a new parameterization of 3D Gaussians for that) and we optimize the Gaussians with Gaussian Splatting rendering. You can see this as a new and realistic texturing tool for the mesh.
4. **(Optional) High-res Texture extraction**: The hybrid representation is cool, but you may want a traditional UV texture with a PNG, so that you could directly import and visualize your colored mesh in Blender, Unity, Unreal, _etc_. The problem is, the coarse mesh extraction part only provides a mesh with vertex colors, which is a very poor tool for texturing a mesh. Therefore, we propose this last, optional phase, during which we optimize a `PNG` image mapped on the surface of the mesh to obtain a UV texture that you can use in traditional software.

In practice, here is what you need to know about the different stages and what impact they have on the quality of the mesh:
- **Coarse optimization**: This part is super important to get a good-looking mesh. If you try to extract a mesh directly from the vanilla Gaussian Splatting, you will get a low-quality result, because the Gaussians are too chaotic and not aligned enough with the surface.
- **Refinement**: This part does not provide a huge improvement concerning the quality of the surface, but makes the surface smoother where it is needed (which is generally much cooler) and is necessary to get the good-looking hybrid representation as well as the high-res texture image.

I hope you'll find this message helpful!
