### ISSUE TITLE
Question about how to remove the verticies lines.

### ISSUE THREAD

**Issue by kitmallet** [Anttwo/SuGaR#119]
Hello @Anttwo I have done a large interior scan which is quite nice. I used 660 photos with 800x1200 resolution. However, the vertices are showing quite a bit when zoomed in.

Wide shot of pub:
![pub_wide_shot](https://github.com/Anttwo/SuGaR/assets/116766385/5937c3cc-6a34-4344-9c99-fe64fdb4c233)

Close up of pub:
![pub_close_up](https://github.com/Anttwo/SuGaR/assets/116766385/e9ce1e33-3825-421a-8fb6-0aa28ef17bc7)

What can be done to remove these lines which show each face?

Thanks again!

**Comment by Anttwo** [comment]
Hello @kitmallet,

Indeed, the scan is really nice, I love it!

Sure, I actually know why you have these lines between triangles, it's perfectly normal and avoidable.

<br>

**1) The short answer:**

The white lines between the triangles are due to the Texture interpolation method you use in your rendering software as well as our UV unwrapping method (which is currently a little dumb).

I suppose your rendering software uses Linear Texture interpolation by default. Please try to use "Closest pixel" Texture interpolation and the texture should be rendered perfectly fine!

<br>

**2) The long answer (to understand what's happening):**

To compute a texture for a mesh, we first need to "unwrap" the mesh with a UV map, which maps every triangle to a set of pixels in the texture image. Generally, you try to preserve some spatial consistency between the 3D geometry and the UV map: two triangles that are close to each other in the 3D mesh should also be close to each other in the UV map. But this problem is (highly) not trivial to solve!

Consequently, here, we propose a very simple (but very dumb) way to unwrap the mesh: we just map all triangles next to each other, at random locations in the UV map. It works well, but it can produce artifacts depending on the texture interpolation method you use in your software.
Texture interpolation is the method you use to render the color of a triangle on the 3D mesh, using the pixel colors in the texture: Should you perform linear interpolation between the colors of neighbor pixels in the texture (this corresponds to the "Linear" setting inside Blender) or should you just use the color of the closest pixel in the texture (this corresponds to the "Closest" setting inside Blender)?

You can see the difference in Blender: If you use "Closest", the texture will be rendered perfectly fine. But if you use "Linear", you will see some white lines between triangles, because Blender interpolates between the color of the right pixels and the color of wrong pixels in the neighborhood (i.e. pixels close to the right pixel in the UV map, but that map to totally different triangles on the mesh).

Example of linear interpolation:
![linear_interpolation](https://github.com/Anttwo/SuGaR/assets/65666237/f30679b4-9999-4d9d-b0a6-25d8fbabb370)
![linear_interpolation_2](https://github.com/Anttwo/SuGaR/assets/65666237/80b3dbd2-dcc1-4d4e-986d-4c306c4f8e57)

Example of closest pixel (no interpolation):
![closest_pixel](https://github.com/Anttwo/SuGaR/assets/65666237/2c516820-bf25-4620-ad97-3efb07c38af4)
![closest_pixel_2](https://github.com/Anttwo/SuGaR/assets/65666237/300088f6-1423-459c-9f6a-1364910d942a)


Moreover, I recommend using an "Emission shader" for visualizing SuGaR's meshes within Blender. It's a very straightforward way to render the colored texture without getting any other light/shadow effects in the way (indeed, because the texture is computed from input images, shadows from the original scene are already baked in the texture). Another way to do it would be to use an Ambient lighting, but within Blender an Emission shader is more straightforward in my opinion.

**Comment by kitmallet** [comment]
Thank you for the easiest fix I have had so far @Anttwo !!! Not to throw in high res pictures as we now have just about everything solved. 
Kit

**Comment by DYH200009** [comment]
Can you tell me how to achieve this effect on meshlab  ？Please ~
