### ISSUE TITLE
A lot of outliers in mesh when using custom dataset

### ISSUE THREAD

**Issue by Student204161** [Anttwo/SuGaR#169]
Hi, I've tried using SuGaR on my own dataset and I get a not-so-good result, as there is a lot of outliers in my mesh:

![image](https://github.com/Anttwo/SuGaR/assets/97975723/ba407a60-e80c-4b10-bc92-a5381a12c7b3)
The above was generated with default params when using "sdf" as regularization, but I get the same when using "density".

These results are generated from a gaussian splatting checkpoint of 30k iterations (default params), which creates this following point cloud
![image](https://github.com/Anttwo/SuGaR/assets/97975723/9963639c-89c6-410e-a4a7-ad3e96a27ce7)

So I have methods of removing most of the outliers from the point cloud, but is there a way for SuGaR to use the updated point cloud? I'm wondering if it's feasible...

For clarity, the data is supposed to be a scene of a Aloe Vera plant that looks like this:
![image](https://github.com/Anttwo/SuGaR/assets/97975723/640fb726-cb1b-4b63-8c62-2293311f2b7f)

Thanks for the attention.

**Comment by Anttwo** [comment]
Hello @Student204161,

I have a few questions for you:

<br>

**Question 1: May I ask, are you using a dataset with segmented objects/masked background (as the background looks black in your images, but it seems there is additional color in your reconstruction)?**

The current version of SuGaR has trouble with images of segmented objects, as flat monochrome backgrounds create artifacts. But I actually fixed this problem and will push a new version of the code in a few days that can handle images of segmented objects (with masked background).

This fix could probably improve the quality of your reconstruction!

<br>

**Question 2: Also, may I have more information about your capture (is it a 360° trajectory around the object, for example)?**

This can impact the final results and produce artifacts. 
Generally, even in vanilla Gaussian Splatting, artifacts in background are unavoidable as there is usually a lot of ambiguity for background objects (because they are observed only from a few points of view). When you reconstruct the entire world as a surface (as SuGaR does), obtaining some weird small surface elements in the background is quite unavoidable without (a) additional images that better show the background or (b) a better prior about the geometry of objects existing in the real world, for example a learned prior.

I hope this message helps you!

**Comment by Student204161** [comment]
Hi @Anttwo 

Thanks for the quick response!

For Q1, yes it's a dataset with segmented objects/masked background - awesome, looking forward to the new update!

For Q2, yes it's almost a 360 degree trajectory around the object - the object is sitting on a table so I've tried covering all angles pointing to the object with the camera above the table.

Thanks for the help, I'll be sure to run the dataset after the new update and post results here :)

**Comment by Student204161** [comment]
Closing issue for the immediate time being

**Comment by 39GodMissing** [comment]
> 你好
> 
> 感谢您的快速回复！
> 
> 对于 Q1，是的，它是一个具有分割对象/遮罩背景的数据集 - 太棒了，期待新的更新！
> 
> 对于 Q2，是的，它几乎是围绕物体的 360 度轨迹 - 物体坐在桌子上，所以我尝试用桌子上方的摄像头覆盖指向物体的所有角度。
> 
> 感谢您的帮助，我一定会在新的更新后运行数据集，并在此处发布结果:)

Hello, may I ask how your final running result was? Can you share it? Thank you very much！
