### ISSUE TITLE
Confusion about cum_probs in  sample_points_in_gaussians()

### ISSUE THREAD

**Issue by Howie-Ye** [Anttwo/SuGaR#178]
I am wondering why there is a cum_probs here?  

It should be  areas / areas.sum(dim=-1, keepdim=True) . 

Since sampling frequency (or number of sampled points) should be proportional to the size of the areas, and the points evenly sampled when areas is ones_like. 

But now those with larger indices are sampled more.

**Comment by Anttwo** [comment]
Hello @Howie-Ye,

You are absolutely right.
I actually noticed this mistake some time ago, but forgot to push the change (since I have other changes waiting in my commits, that are related to Gaussian Frosting).

I remember doing some tests when I noticed it, to check if the cumsum was decreasing performance. 
Surprisingly, it does not seem to change the result.

I just have a few other things to check, and I will push this change.

**Comment by Howie-Ye** [comment]
> Hello @Howie-Ye,
> 
> You are absolutely right. I actually noticed this mistake some time ago, but forgot to push the change (since I have other changes waiting in my commits, that are related to Gaussian Frosting).
> 
> I remember doing some tests when I noticed it, to check if the cumsum was decreasing performance. Surprisingly, it does not seem to change the final result. I suppose that, even if points at the start of the list are selected more frequently with the cumsum, all Gaussians end up to be regularized enough in the end.
> 
> I just have a few other things to check, and I will push this change.

Thanks for your reply and explanation that is quite reasonable.  

I will close the issue.
