### ISSUE TITLE
MemoryError: bad allocation when extracting corase mesh

### ISSUE THREAD

**Issue by XOURTNEY** [Anttwo/SuGaR#22]
Hi Anttwo！
Thanks for the amazing work and the elegant code!  
I ran the project just now, and I encontered the following error just after console printed "Decimating and cleaning meshes".
——————————————————————————————————————————
-----Decimating and cleaning meshes-----

Processing decimation target: 1000000
Decimating foreground mesh...
Traceback (most recent call last):
  File "D:\ExtractMesh\SuGaR\train.py", line 141, in <module>
    coarse_mesh_path = extract_mesh_from_coarse_sugar(coarse_mesh_args)[0]
  File "D:\ExtractMesh\SuGaR\sugar_extractors\coarse_mesh.py", line 427, in extract_mesh_from_coarse_sugar
    decimated_o3d_fg_mesh = o3d_fg_mesh.simplify_quadric_decimation(decimation_target)
MemoryError: bad allocation
——————————————————————————————————————————
I ran the code with 32GB of memory but encountered an issue. May I ask about the memory requirements for running this project？
Looking forward to your reply!

**Comment by Anttwo** [comment]
Hi XOURTNEY,

For every scene, I ran SuGaR with 32GB of memory and it never uses all the memory. I actually am pretty sure it can run with less than 20GB (maybe even 16GB, since we don't use as many Gaussians as the original 3DGS paper?); I'm going to do some tests on a 16GB memory GPU.

Therefore, your error is surprising; could you tell me how many Gaussians you have in your scene?

**Comment by XOURTNEY** [comment]
Hi Anttwo, 

Sorry Anttwo, I wasn't clear yesterday. I ran SuGaR with 32GB RAM and 8GB 4060ti and the error message was "MemoryError: bad allocation". I assumed it was my 32GB of RAM that was low, not the 8GB of RAM for the graphics processor, for the following reasons.

First, I thought that when SuGaR needed to extract the mesh, it meant that the most stressful time period for the GPU had passed (I'm not sure if I get this correct). So I think the extraction progress may not be causing the GPU to run out of memory?

Secondly, I looked at line 427 which is causing the error. Just before line 427, lines 398-400 show "bg_points.cpu()", "bg_colors.cpu()", and "bg_normals.cpu()" respectively. Do these calculations and after take up 32GB of memory?

Sorry if I still misunderstood the error! Thank you very much for helping me with my testing!

The Gaussians in the scene I ran yesterday was 614821. And the corresponding 7000 epoch point_cloud.ply is about 147MB.

Looking forward to yoru reply!

**Comment by yuedajiong** [comment]
I run on 12G CPU, titan-xp.

https://github.com/Anttwo/SuGaR/issues/26

Just try small/simple object reconstruction firstly, please.

**Comment by Anttwo** [comment]
Hello @XOURTNEY ,

Oh I'm sorry, you were talking about the CPU, I misread your message (I should have guessed since the error occured during mesh decimation).

Your number of Gaussians look decent, and the error comes from Open3D's decimation function, so it's not easy to guess what could be the problem...
As @yuedajiong said, trying simpler objects first can be a good way to investigate what your problem is. 
Have you tried on a scene from a standard datasets (like the deepblending scenes provided by the authors of original 3DGS https://github.com/graphdeco-inria/gaussian-splatting)?

**Comment by cubantonystark** [comment]
The problem manifests during the decimation process (segmentation error). My humble theory is the actual cause is the poisson_depth parameter in sugar_extractors/coarse_mesh.py. Try adjusting it to 8 and see if that works. 10 might be too much for even that amount of RAM.

**Comment by XOURTNEY** [comment]
I solve the problem by change my device to A100.
