### ISSUE TITLE
[Open3D WARNING] Read PLY failed: unable to open file: 

### ISSUE THREAD

**Issue by kitmallet** [Anttwo/SuGaR#27]
Greetings from Canada Antoine,
I am a filmmaker and have been working with various aspects of Virtual Production since its inception. I am by no means a computer expert, and to some, this may be a simple issue to solve. Everything works great up to the point of "optimize a SuGaR model".

Loading mesh to bind to:
./output/coarse_mesh\ball2\sugarmesh_coarse\ball2\3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000.ply...
RPly: Unable to open file
[Open3D WARNING] Read PLY failed: unable to open file: ./output/coarse_mesh\ball2\sugarmesh_coarse\ball2\3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000.ply
Mesh to bind to loaded.
Binding radiance cloud to surface mesh...
Traceback (most recent call last):
  File "C:\Users\conan\SuGaR\train.py", line 160, in <module>
    refined_sugar_path = refined_training(refined_args)
  File "C:\Users\conan\SuGaR\sugar_trainers\refine.py", line 393, in refined_training
    sugar = SuGaR(
  File "C:\Users\conan\SuGaR\sugar_scene\sugar_model.py", line 322, in __init__
    scales = scales.clamp_min(0.0000001).reshape(len(faces_verts), -1, 1).expand(-1, self.n_gaussians_per_surface_triangle, 2).clone().reshape(-1, 2)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1] because the unspecified dimension size -1 can be any value and is ambiguous

Merci pour le travail que vous faites. Je pense que cela pourrait changer le monde du cinéma.
Best,
Kit

**Comment by yuedajiong** [comment]
1.  use Gaussian-Splatting to train and save out checkpoint.
2.  use SuGaR to train.

example:

cd gaussian_splatting
python -Bu train.py -s ../../data/image/wizard/ -m ../output/gauss/ --iterations 30000 --save_iterations 7000 30000 --checkpoint_iterations 7000 30000
cd ..

python -Bu train_coarse_density.py --s ../data/image/wizard/ --c ./output/gauss/

**Comment by nehilsood** [comment]
Facing same issues even after using the commands @yuedajiong mentioned
-----------
Loading mesh to bind to:
./output/coarse_mesh\natraj\sugarmesh_coarse\natraj\3Dgs7000_densityestim02_sdfnorm02_level03_decim1000000.ply...
RPly: Unable to open file
[Open3D WARNING] Read PLY failed: unable to open file: ./output/coarse_mesh\natraj\sugarmesh_coarse\natraj\3Dgs7000_densityestim02_sdfnorm02_level03_decim1000000.ply
Mesh to bind to loaded.
Binding radiance cloud to surface mesh...
Traceback (most recent call last):
  File "C:\Users\Administrator\work\SuGaR\train.py", line 162, in <module>
    refined_sugar_path = refined_training(refined_args)
  File "C:\Users\Administrator\work\SuGaR\sugar_trainers\refine.py", line 393, in refined_training
    sugar = SuGaR(
  File "C:\Users\Administrator\work\SuGaR\sugar_scene\sugar_model.py", line 322, in __init__
    scales = scales.clamp_min(0.0000001).reshape(len(faces_verts), -1, 1).expand(-1, self.n_gaussians_per_surface_triangle, 2).clone().reshape(-1, 2)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1] because the unspecified dimension size -1 can be any value and is ambiguous
-----------------------
@Anttwo Please look into this
-----------------------

Commands I used:
1. python -Bu gaussian_splatting/train.py -s data/natraj -m outputs/natraj --iterations 15000 --save_iterations 7000 15000 --checkpoint_iterations 7000 15000
2. python -Bu train_coarse_density.py --s data/natraj --c outputs/natraj/
3. python -Bu train.py -s data/natraj -c outputs/natraj/ -r "density"
-----------------------

1st two commands worked fine
3rd command showed the error above

**Comment by binghui-z** [comment]
> Greetings from Canada Antoine, I am a filmmaker and have been working with various aspects of Virtual Production since its inception. I am by no means a computer expert, and to some, this may be a simple issue to solve. Everything works great up to the point of "optimize a SuGaR model".
> 
> Loading mesh to bind to: ./output/coarse_mesh\ball2\sugarmesh_coarse\ball2\3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000.ply... RPly: Unable to open file [Open3D WARNING] Read PLY failed: unable to open file: ./output/coarse_mesh\ball2\sugarmesh_coarse\ball2\3Dgs7000_sdfestim02_sdfnorm02_level03_decim1000000.ply Mesh to bind to loaded. Binding radiance cloud to surface mesh... Traceback (most recent call last): File "C:\Users\conan\SuGaR\train.py", line 160, in refined_sugar_path = refined_training(refined_args) File "C:\Users\conan\SuGaR\sugar_trainers\refine.py", line 393, in refined_training sugar = SuGaR( File "C:\Users\conan\SuGaR\sugar_scene\sugar_model.py", line 322, in **init** scales = scales.clamp_min(0.0000001).reshape(len(faces_verts), -1, 1).expand(-1, self.n_gaussians_per_surface_triangle, 2).clone().reshape(-1, 2) RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1, 1] because the unspecified dimension size -1 can be any value and is ambiguous
> 
> Merci pour le travail que vous faites. Je pense que cela pourrait changer le monde du cinéma. Best, Kit

I meet the same error, do you have solved this problem?

**Comment by kitmallet** [comment]
I did solve it. However, there was a mistake in prompt #2.

python -Bu train_coarse_density.py --s data/natraj --c outputs/natraj/
should be:
python -Bu train_coarse_density.py -s data/natraj -c outputs/natraj/

By removing the "-" before the s and c I got a result.
Best,
Kit
