### ISSUE TITLE
Question about the implementation details

### ISSUE THREAD

**Issue by zhao-yiqun** [Anttwo/SuGaR#5]
Hi

Thanks for your nice work. I have some implementation details about how to get the nearest g* in equation (3). Hope this can get the details from you.

You mentioned this in Sec.5.1

> To compute the density values of points
from a gaussian g, we sum only the gaussian functions from
the 16 nearest gaussians of g and update the list of nearest
neighbors every 500 iterations.

For the regularization from 9000-15000 steps, you will sample different p from the gaussian distribuion in equation (8).
Therefore, I wonder how you can keep the nearest list of g unchanged for each p at different iteration(update every 500 iterations)? Based on my understanding, the p sampled from each splats varied at different iterations.

Thanks in advance
Yiqun

**Comment by Anttwo** [comment]
Hi Yiqun,

It's because we do not use the neighbors of the point $p$, but the neighbors of the Gaussian $g$ from which the point $p$ is sampled.
In other words, we update the neighbor Gaussians of all Gaussians every 500 iterations. Then, we suppose that the density of a point $p$ sampled using a Gaussian $g$ will mostly depend on the gaussians that are close to $g$ (including $g$, of course).

I hope this helps you!
Best
