### ISSUE TITLE
How to improve my rendering result?

### ISSUE THREAD

**Issue by WN-Wolf** [Anttwo/SuGaR#96]
Hi @Anttwo,
Thanks you for your previous help, I have got my rendering result now. 

https://github.com/Anttwo/SuGaR/assets/75304226/d715eee5-7703-4002-8a52-d707f5477110

https://github.com/Anttwo/SuGaR/assets/75304226/6c9acdf7-5583-4b56-8323-2d3dc059a8a3

But, my result isn't very well. Can you tell me how to improve my result and get result like yours?

https://github.com/Anttwo/SuGaR/assets/75304226/bde62885-a6c2-4361-b8e9-b90931bd13d3

**Comment by Anttwo** [comment]
Hey @WN-Wolf,

Thank you for posting your results, it's nice to see them!

Alright, here are a few tips and observations:

**Concerning the quality of the background**
This is expected, unfortunately: Because (a) your video is a close-up capture of the character, and (b) the background is monochrome in your video and has no particular details, you will necessary get some small artifacts in your background. 
But this may not be a problem, as you scene is heavily focused on the character and I suppose you want to reconstruct a good-looking character rather than a good-looking background. 

**Concerning the quality of the character**
The character is actually not so bad if you take a look at it! Here are a few tips:
1. **Reduce the number of vertices by using `--low_poly`**. The surface is indeed slightly irregular. This is probably because your character is pretty simple (smooth surface and shapes, etc) so you may not need this many vertices for this scene. 
Using too many vertices for simple shapes may cause some slight irregularities like the ones you have. You can try to use the `--low_poly` argument for `train.py`, instead of the default configuration which is `--high_poly`. 
For instance, I used `--low_poly` for the white and red knight in the examples, and it still looks pretty good. On the contrary, I used `--high_poly` for the white and blue robot, which has much more small details.
2. **Change the lighting:** I think the lighting makes a lot in the appreciation of a render. In your example, the light source seems to be located under the surface, which does not match the real lighting of your scene and makes it look quite off. 
You should try to replace your current lighting (that uses a light source) by a single ambient lighting with intensity 1 (your software should have this option). This will just display the mesh with the colored texture and no additional lighting computation. This should look much better and be much closer to your actual scene, as the shadow in your scene is already captured in your texture anyway.

If you're using Linux/MacOS (or Windows with WSL2), you can also use the dedicated SuGaR viewer. It lets you visualize the textured mesh with an ambient lighting, as well as the hybrid representation (i.e. the mesh with 3D Gaussians on its surface).

**Comment by nile649** [comment]
hi @WN-Wolf this is related to separate issue. I tried using video that you have provided, but when i convert the video to images. Move the images to /customCOLMAP/input/
and use ```python gaussian_splatting/convert.py -s ../customCOLMAP/```
I only have 2 images. Could you share how you were able to get more number of images

**Comment by WN-Wolf** [comment]
> hi @WN-Wolf this is related to separate issue. I tried using video that you have provided, but when i convert the video to images. Move the images to /customCOLMAP/input/ and use `python gaussian_splatting/convert.py -s ../customCOLMAP/` I only have 2 images. Could you share how you were able to get more number of images

1 For the convenience of uploading, I cropped a short video.  I can't upload whole videos, becasue it too big.
2 For your question:
2.1 You should cd ./customCOLMAP/distorted/sparse
2.2 You should see several sub-directories named 0/, 1/, etc., each containing a sub-model. Remove all sub-directories except the one containing the largest files, and rename it to 0/. 
2.3 Then, run the command: python gaussian_splatting/convert.py -s ../customCOLMAP/ --skip_matching

**Comment by WN-Wolf** [comment]
> Hey @WN-Wolf,
> 
> Thank you for posting your results, it's nice to see them!
> 
> Alright, here are a few tips and observations:
> 
> **Concerning the quality of the background** This is expected, unfortunately: Because (a) your video is a close-up capture of the character, and (b) the background is monochrome in your video and has no particular details, you will necessary get some small artifacts in your background. But this may not be a problem, as you scene is heavily focused on the character and I suppose you want to reconstruct a good-looking character rather than a good-looking background.
> 
> **Concerning the quality of the character** The character is actually not so bad if you take a look at it! Here are a few tips:
> 
>     1. **Reduce the number of vertices by using `--low_poly`**. The surface is indeed slightly irregular. This is probably because your character is pretty simple (smooth surface and shapes, etc) so you may not need this many vertices for this scene.
>        Using too many vertices for simple shapes may cause some slight irregularities like the ones you have. You can try to use the `--low_poly` argument for `train.py`, instead of the default configuration which is `--high_poly`.
>        For instance, I used `--low_poly` for the white and red knight in the examples, and it still looks pretty good. On the contrary, I used `--high_poly` for the white and blue robot, which has much more small details.
> 
>     2. **Change the lighting:** I think the lighting makes a lot in the appreciation of a render. In your example, the light source seems to be located under the surface, which does not match the real lighting of your scene and makes it look quite off.
>        You should try to replace your current lighting (that uses a light source) by a single ambient lighting with intensity 1 (your software should have this option). This will just display the mesh with the colored texture and no additional lighting computation. This should look much better and be much closer to your actual scene, as the shadow in your scene is already captured in your texture anyway.
> 
> 
> If you're using Linux/MacOS (or Windows with WSL2), you can also use the dedicated SuGaR viewer. It lets you visualize the textured mesh with an ambient lighting, as well as the hybrid representation (i.e. the mesh with 3D Gaussians on its surface).

@Anttwo Thank you for you help! I will try again according to your suggestion.

**Comment by WN-Wolf** [comment]
@Anttwo 
Thanks for your amazing work!
I used `--low_poly` parameter and it became much better than before.

https://github.com/Anttwo/SuGaR/assets/75304226/10fc0c34-3d77-4889-a494-37872e30cf15


https://github.com/Anttwo/SuGaR/assets/75304226/22046411-eef4-4ab4-9a2d-0a6cdb743c6b

When I used `--high_poly` parameter, the result wasn't very well.
![long_hair_render](https://github.com/Anttwo/SuGaR/assets/75304226/20b70d56-c5c3-4508-91fb-60484eac8bdf)

I would like to ask if there is an `--middle_poly` parameter?

**Comment by Anttwo** [comment]
Hello @WN-Wolf,

Great to see that you got a nice looking mesh!

There is no `--middle_poly` config, but you actually don't need it to build your own config! 
Let me explain.

Actually, `--low_poly` and `--high_poly` are just shortcut arguments that provide default values for two parameters used in SuGaR:
- The first is `--n_vertices_in_mesh`, which corresponds to the number of vertices in the extracted mesh.
- The second is `--gaussians_per_triangle`, which corresponds to the number of Gaussians to use in each triangle to build the hybrid representation (i.e. The mesh covered with 3D Gaussians on its surface). When you decrease the number of vertices, you need to increase the number of Gaussians per triangle to keep a similar rendering quality.

The `--low_poly` config uses 200,000 vertices and 6 gaussians per triangle.
The `--high_poly` config uses 1,000,000 vertices and 1 gaussian per triangle.

For instance, if you want a medium config, you can remove the `--low_poly` argument and add `--n_vertices_in_mesh 500_000` and `--gaussians_per_triangle 3` in your command:

```
python train.py -s <path to COLMAP dataset> -c <path to the Gaussian Splatting checkpoint> -r <"density" or "sdf"> --n_vertices_in_mesh 500_000 --gaussians_per_triangle 3
```

This command will run SuGaR and extract a mesh that contains roughly 500,000 vertices and binds 3 Gaussians per triangle.
This would be similar to a ``_medium poly_'' config.

**Comment by WN-Wolf** [comment]
Hi @Anttwo,

Thanks for you reply! Your suggestion is very useful! 
Here is a comparison of the results! The --medium_poly has better performance!

--high_poly
![high_poly](https://github.com/Anttwo/SuGaR/assets/75304226/e33803de-fa31-4ebb-a9f2-b767686f950b)

--low_poly
![low_poly](https://github.com/Anttwo/SuGaR/assets/75304226/5ce0b7ed-cdef-4b05-b02f-667e9009076b)

--medium_poly
![``medium_poly''](https://github.com/Anttwo/SuGaR/assets/75304226/795f0a23-a347-4e97-8da1-38a6db8522b0)
